const quotes = [
  "Addiction is not a choice. It is a disease. But with the right treatment, people can recover.",
  "There is help available. You don't have to fight this alone.",
  "Recovery is possible. One day at a time.",
  "Drugs can steal your dreams. Don't let them.",
  "You are stronger than your addiction.",
  "You are worthy of a life free from drugs.",
  "Drugs don't solve problems, they create them.",
  "There is hope. There is help. There is a future without drugs.",
  "Education is the best vaccine against drug abuse.",
  "Your mind and body are amazing. Don't abuse them.",
  "Don't let drugs control your life. Take control and get help.",
  "Be proud of yourself for choosing a drug-free life.",
  "Drugs are a temporary escape with a lifetime of consequences.",
  "Drugs can dim your future. Choose to shine.",
  "Say no to drugs and open the door to a world of possibilities.",
  "Your future is worth fighting for. Don't let drugs steal it.",
  "Drugs may seem like a way to fit in, but they can leave you feeling alone.",
  "Drugs can break promises, not hearts. Choose a life free from addiction.",
  "There's no shame in asking for help. It's a sign of strength.",
  "Don't let drugs write your story. Be the author of your own success.",
  "The only high worth getting is the feeling of accomplishment.",
  "Drugs are expensive. Invest in yourself, not your addiction.",
  "There's beauty in living a drug-free life. Discover it for yourself.",
  "You are capable of amazing things. Don't let drugs hold you back.",
  "Believe in yourself. You are strong enough to overcome addiction.",
  "The best way to say no to drugs is to say yes to life.",
  "Drugs cost you more than just money.",
  "Drugs are not the answer, they are the problem.",
  "Don't choose the drug, choose the life.",
  "Sobriety is a journey, not a destination.",
  "Drugs make you feel good for a while, but the damage they do can last a lifetime.",
  "Don't let drugs control your life, take control and live drug-free.",
  "Drugs may make you feel like you're in control, but in reality, they're controlling you.",
  "The only way to win against drugs is not to play the game.",
  "Every time you choose drugs, you're choosing to lose.",
  "The real high comes from living a clean and sober life.",
  "Drugs don't just ruin your body, they destroy your mind and soul.",
  "Drugs are a temporary solution to a permanent problem.",
  "You don't need drugs to escape reality, you need courage to face it.",
  "Don't let drugs steal your dreams.",
  "Life is too precious to waste on drugs.",
  "Drugs may seem like a shortcut, but they always lead to a dead end.",
  "The only way to break the cycle of addiction is to break free from drugs.",
  "Don't let drugs write the story of your life.",
  "Drugs are like quicksand, the more you struggle, the deeper you sink.",
  "Choose life, not drugs.",
  "Drugs don't discriminate, they destroy everyone in their path.",
  "The best high is the natural high of living a drug-free life.",
  "The only thing drugs offer is a life of regret.",
  "Every day is a new chance to say no to drugs and yes to a brighter future.",
];

export default quotes;
